package com.hoppingmall.settlement.exception

import com.hoppingmall.settlement.exception.code.SettlementErrorCode

class SettlementInvalidStatusException : SettlementException(SettlementErrorCode.SETTLEMENT_INVALID_STATUS)
