package com.hoppingmall.settlement.exception

import com.hoppingmall.settlement.exception.code.SettlementErrorCode

class SettlementSellerNotFoundException : SettlementException(SettlementErrorCode.SETTLEMENT_SELLER_NOT_FOUND)
