apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/notification-service
images:
  - name: notification-service
    newName: localhost:5001/notification-service
    newTag: fix5
