feat:
  - changed-files:
      any-glob-to-any-file:
        - "module-*/**/*.kt"
        - "**/application-*.yml"

fix:
  - changed-files:
      any-glob-to-any-file:
        - "*/**/*.kt"
        - "**/*.md"

refactor:
  - changed-files:
      any-glob-to-any-file:
        - "*/**/*.kt"

test:
  - changed-files:
      any-glob-to-any-file:
        - "*/**/test/**/*.kt"
        - "**/test/**"

docs:
  - changed-files:
      any-glob-to-any-file:
        - "**/*.md"
        - "README.md"

chore:
  - changed-files:
      any-glob-to-any-file:
        - "**/.gitignore"
        - "**/build.gradle.kts"
        - "**/settings.gradle.kts"
