feat:
  - changed-files:
      - "module-*/**/*.kt"
      - "**/application-*.yml"

fix:
  - changed-files:
      - "*/**/*.kt"
      - "**/*.md"

refactor:
  - changed-files:
      - "*/**/*.kt"

test:
  - changed-files:
      - "*/**/test/**/*.kt"
      - "**/test/**"

docs:
  - changed-files:
      - "**/*.md"
      - "README.md"

chore:
  - changed-files:
      - "**/.gitignore"
      - "**/build.gradle.kts"
      - "**/settings.gradle.kts"
