coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 90%
        threshold: 1%

flags:
  user:
    paths:
      - "src/main/kotlin/com/hoppingmall/mall/user"
      - "src/test/kotlin/com/hoppingmall/mall/user"

comment:
  layout: "diff, flags, files"
  behavior: default
