spring:
  data:
    redis:
      host: redis.hoppingmall.svc.cluster.local
      port: 6379

  cloud:
    gateway:
      routes:
        - id: user-service-public
          uri: http://user-service.hoppingmall.svc.cluster.local:8082
          predicates:
            - Path=/api/v1/users/signup,/api/v1/users/login,/api/v1/auth/refresh

        - id: product-service-statistics
          uri: http://product-service.hoppingmall.svc.cluster.local:8083
          predicates:
            - Path=/api/v1/admin/product-statistics/**
          filters:
            - name: JwtValidation

        - id: payment-service-admin-coupons
          uri: http://payment-service.hoppingmall.svc.cluster.local:8085
          predicates:
            - Path=/api/v1/admin/coupons/**
          filters:
            - name: JwtValidation

        - id: settlement-service-admin-settlements
          uri: http://settlement-service.hoppingmall.svc.cluster.local:8086
          predicates:
            - Path=/api/v1/admin/settlements/**
          filters:
            - JwtValidation

        - id: payment-service-admin-dlq
          uri: http://payment-service.hoppingmall.svc.cluster.local:8085
          predicates:
            - Path=/api/v1/admin/dlq/**
          filters:
            - JwtValidation

        - id: user-service
          uri: http://user-service.hoppingmall.svc.cluster.local:8082
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**,/api/v1/sellers/**,/api/v1/admin/sellers/**,/api/v1/memberships/**
          filters:
            - JwtValidation

        - id: notification-service
          uri: http://notification-service.hoppingmall.svc.cluster.local:8081
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - JwtValidation

        - id: product-service-products
          uri: http://product-service.hoppingmall.svc.cluster.local:8083
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: JwtValidation

        - id: product-service-categories
          uri: http://product-service.hoppingmall.svc.cluster.local:8083
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - name: JwtValidation

        - id: product-service-inventories
          uri: http://product-service.hoppingmall.svc.cluster.local:8083
          predicates:
            - Path=/api/v1/inventories/**
          filters:
            - name: JwtValidation

        - id: product-service-reviews
          uri: http://product-service.hoppingmall.svc.cluster.local:8083
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - name: JwtValidation

        - id: product-service-wishlists
          uri: http://product-service.hoppingmall.svc.cluster.local:8083
          predicates:
            - Path=/api/v1/wishlists/**
          filters:
            - name: JwtValidation

        - id: product-service-dashboard
          uri: http://product-service.hoppingmall.svc.cluster.local:8083
          predicates:
            - Path=/api/v1/seller/dashboard/**
          filters:
            - name: JwtValidation

        - id: settlement-service-seller-settlements
          uri: http://settlement-service.hoppingmall.svc.cluster.local:8086
          predicates:
            - Path=/api/v1/seller/settlements/**
          filters:
            - JwtValidation

        - id: order-service-orders
          uri: http://order-service.hoppingmall.svc.cluster.local:8084
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: JwtValidation

        - id: order-service-cart-items
          uri: http://order-service.hoppingmall.svc.cluster.local:8084
          predicates:
            - Path=/api/v1/cart-items/**
          filters:
            - name: JwtValidation

        - id: order-service-shipping
          uri: http://order-service.hoppingmall.svc.cluster.local:8084
          predicates:
            - Path=/api/v1/shipping/**
          filters:
            - name: JwtValidation

        - id: order-service-refunds
          uri: http://order-service.hoppingmall.svc.cluster.local:8084
          predicates:
            - Path=/api/v1/refunds/**
          filters:
            - name: JwtValidation

        - id: payment-service-payments
          uri: http://payment-service.hoppingmall.svc.cluster.local:8085
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: JwtValidation

        - id: payment-service-points
          uri: http://payment-service.hoppingmall.svc.cluster.local:8085
          predicates:
            - Path=/api/v1/points/**
          filters:
            - name: JwtValidation

        - id: payment-service-point-policies
          uri: http://payment-service.hoppingmall.svc.cluster.local:8085
          predicates:
            - Path=/api/v1/point-policies/**
          filters:
            - name: JwtValidation

        - id: payment-service-coupons
          uri: http://payment-service.hoppingmall.svc.cluster.local:8085
          predicates:
            - Path=/api/v1/coupons/**
          filters:
            - name: JwtValidation

management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin.hoppingmall.svc.cluster.local:9411/api/v2/spans

logging:
  level:
    root: INFO
    com.hoppingmall: INFO
    org.springframework.cloud.gateway: INFO
