spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        legacy_id_generator_strategy: true

  data:
    redis:
      host: localhost
      port: 6379

  devtools:
    restart:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.schema: debug
    org.hibernate.tool.hbm2ddl: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret: my-secret-secret-secret-secret-secret-key-123456789
  access-expiration-ms: 3600000 # 1 hour
  refresh-expiration-ms: 86400000 # 24 hour

file:
  upload:
    base-upload-dir: D:/hoppingmall
    max-file-size: 5242880 # 5MB
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - gif
      - webp
    allowed-domains:
      - product
    sub-directory: images
