apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/product-service
images:
  - name: product-service
    newName: localhost:5001/product-service
    newTag: latest
