apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/settlement-service
images:
  - name: settlement-service
    newName: localhost:5001/settlement-service
    newTag: f31869c
