apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/payment-service
images:
  - name: payment-service
    newName: localhost:5001/payment-service
    newTag: fix5
