apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: user-service-destrule
  namespace: hoppingmall
spec:
  host: user-service
  subsets:
    - name: stable
      labels:
        app: user-service
    - name: canary
      labels:
        app: user-service
